name: IpacPER
version: '${project.version}'
main: aplini.ipacper.IpacPER
api-version: '1.19'

permissions:

  IpacPER.onPlayerAdvancementDoneEvent:
    default: true
    description: '允许玩家获取成就'

  IpacPER.onPlayerSpectatorTPGUI:
    default: true
    description: '允许旁观模式使用GUI进行传送'

  IpacPER.onPlayerKickForSpamming:
    default: false
    description: '绕过滥发消息踢出'